backend:
  name: git-gateway

media_library:
  name: cloudinary
  config:
    cloud_name: 
    api_key: 
    output_filename_only: true

logo_url: 'https://d33wubrfki0l68.cloudfront.net/f1afd154dd1bd09e6957dce7291bfc56834b4489/b2edb/assets/img/brand/logo.svg'

collections:

  - label: Foto de Capa

  - label: "Sobre"
    name: "sobre"
    folder: "collections/_sobre"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Ícone", name: "icon", widget: "string"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Serviços"
    name: "servicos"
    folder: "collections/_servicos"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Link", name: "link", widget: "string"}
      - {label: "Imagem", name: "image", widget: "image"}
      - {label: "Conteúdo", name: "body", widget: "markdown"}

  - label: "Portfólio"
    name: "portfolio"
    folder: "collections/_portfolio"
    create: true
    fields:
      - {label: "Titulo", name: "title", widget: "string"}
      - label: "Tag"
        name: "tag"
        widget: "select"
        options: ["website", "identidade", "logotipo"]
      - {label: "Imagem", name: "image", widget: "image"}